# This is a basic workflow to help you get started with Actions

name: Generate Manual to Github Pages

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    # push:
    #   branches: [ "main" ]
    # pull_request:
    #   branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        inputs:
            branch:
                description: "选择分支"
                required: true
            
            software:
                description: "软件名称（StereoMap, SAW, SDAS, etc.）"
                required: true
                default: "StereoMap"
            
            software_version:
                description: "软件版本（4.2, 4.1, etc.）"
                required: true
                default: "4.2"

            software_language:
                description: "软件语言（en, cn, etc.）"
                required: true
                default: "cn"


env:
    NODE_MODULES_DIR: /Users/huifang/github/node_modules
    NVM_DIR: '/Users/huifang/.nvm'
    NODE_PATH: '/Users/huifang/.nvm/versions/node/v16.16.0/bin'
    PATH: '/Users/huifang/.nvm/versions/node/v16.16.0/bin:/bin:/usr/bin::$PATH'

defaults:
    run:
        shell: sh
        working-directory: /Users/huifang/github/build_stereoTools_manual

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Headworks:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@${{ inputs.branch }}

      # # Enter directory of codes
      # - name: Enter dir
      #   run: mkdir -p $ROOT_DIR && cd $ROOT_DIR

      # PWD
      - name: PWD
        run: |
          pwd
          echo branch ${{ inputs.branch }}
          echo software ${{ inputs.software }}
          echo software_version ${{ inputs.software_version }}
          echo software_language ${{ inputs.software_language }}
      
      # Clear all 
      - name: Clear all
        run: rm -rf *
  

  Get_software_repo:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: Headworks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Git repo
        run: |
          git clone -b ${{ inputs.branch }} https://github.com/STOmics/StereoMap.git 
      
  
  Genrate_software_manual:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [Headworks, Get_software_repo]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Copy node_modules 
      - name: Copy node_modules
        working-directory: /Users/huifang/github/build_stereoTools_manual/StereoMap
        run: cp -r ${{ env.NODE_MODULES_DIR }} ./

      # # Replace H\&E to H&E
      - name: Replace H\&E to H&E
        working-directory: /Users/huifang/github/build_stereoTools_manual/StereoMap
        run: grep "H\\\&E" -rl --include="*.md" . | xargs  sed -i '' "s/H\\\&E/H\&E/g"

      # Runs a command to generate _book
      - name: Generate _book
        working-directory: /Users/huifang/github/build_stereoTools_manual/StereoMap
        run: ${{ env.NODE_PATH }}/gitbook build

      # Replace 
      - name: Replace 
        working-directory: /Users/huifang/github/build_stereoTools_manual/StereoMap
        run: |
          mv _book docs
          grep mark{background:#fff -rl docs | xargs sed -i '' 's/mark{background:#fff/mark{background:#fff/g'

          if [ -e docs/img/assets ]; then 
            mv docs/.gitbook docs/img 
            grep img/assets -rl docs | xargs sed -i '' 's|img/assets|img/assets|g'
          fi
  
  Upload_docs_to_github:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [Headworks, Get_software_repo, Genrate_software_manual]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Upload docs to github repo
        working-directory: /Users/huifang/github/build_stereoTools_manual
        run: |
          git clone https://github.com/STOmics/StereoTools_manual.git TmpRepo
          # 如果存在 {inputs.software}/{inputs.software_language}/{inputs.software_version} 子目录 则删除
          if [ -d TmpRepo/${{inputs.software}}-Manual/${{inputs.software_language}}/${{inputs.software_version}} ]; then
            rm -rf TmpRepo/${{inputs.software}}-Manual/${{inputs.software_language}}/${{inputs.software_version}}/*    
          fi
          mkdir -p TmpRepo/${{inputs.software}}-Manual/${{inputs.software_language}}/${{inputs.software_version}}

          cp -r StereoMap/docs/* TmpRepo/${{inputs.software}}-Manual/${{inputs.software_language}}/${{inputs.software_version}}/
          
          cd TmpRepo
          git add *
          git commit -m "update:"`date "+%Y%m%d%H%M%S"`
          git push    

  Clear_all:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [Headworks, Get_software_repo, Genrate_software_manual, Upload_docs_to_github ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clear all tmp files
      - name: Clear all tmp files
        working-directory: /Users/huifang/github/build_stereoTools_manual
        run: |
          pwd
          rm -rf *
